### ISSUE TITLE
Custom compression recipes not taking oredict entries as ingredient and/or output

### ISSUE THREAD

**Issue by RBTC** [OmnifactoryDevs/ExtendedCrafting#8] opened 2020-12-24 15:41 UTC
I also posted this to the official one, but it probably won't get fixed there because it's the 1.12.2 version.
Maybe someone here can help me.

**Describe the bug**

In a custom compression recipe, oredict entries are not accepted as ingredient or output.

**To Reproduce**

Try to set an oredict entry as ingredient and/or as output in a custom compression recipe

for example:
mods.extendedcrafting.CompressionCrafting.addRecipe(ore:singularityDraconium, ore:ingotDraconium, 10000, extendedcrafting:material:11, 1250000);

**Expected behavior**

No errors when executing the script and the recipe working with all entries of the used oredict entry.

**Screenshots / Scripts / Logs**

https://pastebin.com/FprduTCZ

**Versions:**

**Minecraft:** 1.12.2
**Forge:** 14.23.5.2854
**Cucumber:** 1.12.2-1.1.3
**Extended Crafting:** version doesn't really matter, but have tried with official-1.5.6; omnifactory-1.6.0 
and omnifactory-1.6.0.2  versions
**CraftTweaker (if applicable):**  4.1.20.607

**Comment by anabsolutesloth** [comment] 2020-12-24 22:23
Quick note, for outputs, you'd want "<ore:singularityDraconium>.firstItem".

**Comment by eutropius225** [comment] 2020-12-24 22:46
As the CraftTweaker log says, this seems like an issue in your script: your output is an `IIngredient` rather than an `IItemStack`. It doesn't make sense for the output to be an `IIngredient`, because it's not obvious what item it should give.

You might want to use `.firstItem` to get the first item from the ore dictionary entry, like so:

```zs
import mods.extendedcrafting.CompressionCrafting;

CompressionCrafting.addRecipe(<ore:singularityDraconium>.firstItem,
    <ore:ingotDraconium>, 10000, <extendedcrafting:material:11>, 1250000);
```

I am closing this, since there's no evidence of unintended behaviour.

**Closed by eutropius225** 2020-12-24 22:46 UTC
